version: "3.9"

services:
  app:
    build: ./app
    ports:
      - "8181:8181"
    environment:
      - API_URL=http://api:5000
    depends_on:
      - api
    volumes:
      - app-data:/app/data

  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - DB_PATH=/data/db.sqlite
    volumes:
      - api-data:/data
      - ./db_init.sql:/data/db_init.sql
    command: ["sh", "-c", "sqlite3 /data/db.sqlite < /data/db_init.sql && python api.py"]

volumes:
  app-data:
  api-data:
